### ISSUE TITLE
Version choice

### ISSUE THREAD

**Issue by mirh** [Dyvinia/StayOnOrigin#5]
Is there a particular reason to prefer 10.5.118 over 10.5.119?

**Comment by Dyvinia** [comment]
not really, it was what i chose at the time

**Comment by mirh** [comment]
So.. then you aren't switching to the newer one, *because*?
I did a dumb hex comparison of the files in each release, and once you discount version number and signing certificate bumps, there's probably a few bytes changed in a bunch of files.
